using BookStoreApi.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using QuestPDF.Fluent;
using QRCoder;
using BookApi.Services;
using Microsoft.AspNetCore.RateLimiting;
namespace BookApi.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class FilesController : ControllerBase
    {

        private readonly BookStoreDbContext _context;
        private readonly EmailService _emailService;
        public FilesController(BookStoreDbContext context, EmailService emailService)
        {
            _context = context;
            _emailService = emailService;

        }
        [HttpPost("upload")]
        public async Task<IActionResult> UploadImage(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                return BadRequest("Please select an image.");
            }

            var allowedExtensions = new[]
            {
                ".jpg",
                ".jpeg",
                ".png"
            };

            var extension = Path.GetExtension(file.FileName)
                                .ToLowerInvariant();

            if (!allowedExtensions.Contains(extension))
            {
                return BadRequest("Only JPG, JPEG and PNG files are allowed.");
            }

            if (file.Length > 5 * 1024 * 1024)
            {
                return BadRequest("File size cannot exceed 5 MB.");
            }

            var uploadFolder = Path.Combine(
                Directory.GetCurrentDirectory(),
                "wwwroot",
                "uploads"
            );

            if (!Directory.Exists(uploadFolder))
            {
                Directory.CreateDirectory(uploadFolder);
            }

            var fileName = Guid.NewGuid().ToString() + extension;

            var filePath = Path.Combine(uploadFolder, fileName);

            using var stream = new FileStream(
                filePath,
                FileMode.Create
            );

            await file.CopyToAsync(stream);

            return Ok(new
            {
                message = "Image uploaded successfully",
                fileName = fileName
            });
        }

        [HttpGet("download/{fileName}")]
        public IActionResult DownloadImage(string fileName)
        {
            var filePath = Path.Combine(
                Directory.GetCurrentDirectory(),
                "wwwroot",
                "uploads",
                fileName);

            if (!System.IO.File.Exists(filePath)) {
                return NotFound("Image not found");
            }

            var contentType="image/" + Path.GetExtension(fileName)
                .TrimStart('.')
                .ToLower();

            return PhysicalFile(filePath, contentType, fileName);
        }

        [HttpGet("books/pdf")]
        [Obsolete]
        public async Task<IActionResult> GenerateBookPdf()
        {
            var books = await _context.Books.ToListAsync();

            var document = QuestPDF.Fluent.Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Text("Book Report")
                        .FontSize(24)
                        .Bold();

                    page.Content()
                        .PaddingTop(20)
                        .Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.ConstantColumn(50);
                                columns.RelativeColumn();
                                columns.RelativeColumn();
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("ID").Bold();
                                header.Cell().Text("Title").Bold();
                                header.Cell().Text("Author").Bold();
                            });

                            foreach (var book in books)
                            {
                                table.Cell().Text(book.Id.ToString());
                                table.Cell().Text(book.Title);
                                table.Cell().Text(book.AuthorId.ToString());
                                table.Cell().Text(book.CategoryId.ToString());
                                table.Cell().Text(book.Price.ToString());
                            }
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by BookApi");
                });
            });

            var pdfBytes = document.GeneratePdf();

            return File(
                pdfBytes,
                "application/pdf",
                "book-report.pdf"
            );
        }

        [HttpGet("books/excel")]
        public async Task<IActionResult> GenerateBookExcel()
        {
            ExcelPackage.License.SetNonCommercialPersonal("Ashish");
            var books = await _context.Books.ToListAsync();

           

            using var package = new ExcelPackage();

            var worksheet = package.Workbook.Worksheets.Add("Books");

            // Headers
            worksheet.Cells[1, 1].Value = "ID";
            worksheet.Cells[1, 2].Value = "Title";
            worksheet.Cells[1, 3].Value = "Author ID";
            worksheet.Cells[1, 4].Value = "Category ID";
            worksheet.Cells[1, 5].Value = "Price";

            // Data
            int row = 2;

            foreach (var book in books)
            {
                worksheet.Cells[row, 1].Value = book.Id;
                worksheet.Cells[row, 2].Value = book.Title;
                worksheet.Cells[row, 3].Value = book.AuthorId;
                worksheet.Cells[row, 4].Value = book.CategoryId;
                worksheet.Cells[row, 5].Value = book.Price;

                row++;
            }

            worksheet.Cells.AutoFitColumns();

            var excelBytes = package.GetAsByteArray();

            return File(
                excelBytes,
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "book-report.xlsx"
            );
        }

        [HttpGet("books/qr/{id}")]
        public async Task<IActionResult> GenerateBookQr(int id)
        {
            var book = await _context.Books
                .FirstOrDefaultAsync(b => b.Id == id);

            if (book == null)
            {
                return NotFound("Book not found.");
            }

            var qrData = $"Book ID: {book.Id}\n" +
                         $"Title: {book.Title}\n" +
                         $"Author ID: {book.AuthorId}\n" +
                         $"Category ID: {book.CategoryId}\n" +
                         $"Price: {book.Price}";

            using var qrGenerator = new QRCodeGenerator();

            using var qrCodeData = qrGenerator.CreateQrCode(
                qrData,
                QRCodeGenerator.ECCLevel.Q
            );

            var qrCode = new PngByteQRCode(qrCodeData);

            byte[] qrImage = qrCode.GetGraphic(20);

            return File(
                qrImage,
                "image/png",
                $"book-{book.Id}-qr.png"
            );
        }

        [HttpPost("books/send-pdf")]
        public async Task<IActionResult> SendBookPdf(string email)
        {
            var books = await _context.Books.ToListAsync();

            var document = QuestPDF.Fluent.Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Text("Book Report")
                        .FontSize(24)
                        .Bold();

                    page.Content()
                        .Column(column =>
                        {
                            foreach (var book in books)
                            {
                                column.Item().Text(
                                    $"ID: {book.Id}, " +
                                    $"Title: {book.Title}, " +
                                    $"Price: {book.Price}"
                                );
                            }
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by BookStoreApi");
                });
            });

            var pdfBytes = document.GeneratePdf();

            await _emailService.SendEmailAsync(
                email,
                "Book Report",
                "Please find the book report attached.",
                pdfBytes,
                "book-report.pdf"
            );

            return Ok("Email sent successfully.");
        }

        [EnableRateLimiting("fixed")]
        [HttpGet]
        public async Task<IActionResult> GetBooks()
        {
            var books = await _context.Books.ToListAsync();

            return Ok(books);
        }
    }

}